### ISSUE TITLE
GC: Reserve Wasm memory for upgrading canisters

### ISSUE THREAD

**Issue by ulan** [dfinity/motoko#2909]
The new mark-compact GC will try to use all 4GB of Wasm memory before giving up and failing with out-of-memory. This potentially leaves no space for pre-upgrade hook to run, so the canister can get into a state that is not upgradable.

Note that the old copying GC doesn't have the issue because it can allocate at most 2GB in a semi-space.

The solution would be to reserve space for upgrading and fail normal messages with OOM earlier. For example, reserve 1GB and fail normal messages with OOM after the heap size exceeds 3GB.

**Comment by crusso** [comment]
Another option might be to stabilize directly to StableMemory, rather than into wasm heap and then copy out. Or possibly do it in chunks, if we have the complexity budget for that.

**Comment by akhi3030** [comment]
Is there a quick fix we could do here in the short term before we end up with too many canisters on the mainnet that can no longer be upgraded because of this problem?

**Comment by nomeata** [comment]
Streaming out candid serialization in a buffered way is something we should do anyways, we can use it also with replies. I don't think it would blow the complexity budget, but maybe the humanpower budget.

**Comment by osa1** [comment]
Just as a reference, buffered serialization was also briefly discussed in https://github.com/dfinity/motoko/issues/2797.

**Comment by crusso** [comment]
I think the quick fix is to do what Ulan suggests, though it's really just a mitigation. Feelings like we are building the plane in flight...

**Comment by crusso** [comment]
@osa1 is Ulan's suggestion easy to add?

**Comment by akhi3030** [comment]
> I think the quick fix is to do what Ulan suggests, though it's really just a mitigation. Feels like we are building the plane in flight...

With a production network, that is precisely what we are doing now :laughing:

**Comment by osa1** [comment]
> @osa1 is Ulan's suggestion easy to add?

Failing with OOM at 3 GiB is easy, but it seems like the current situation with copying GC as the default collector is acceptable ("Note that the old copying GC doesn't have the issue ..."), so I wonder if we should implement buffered serialization instead.

With buffered serialization, we can also pre-allocate the serialization buffer below heap base. That way we don't have to change anything in GC or allocator API, we just adjust heap base pointer depending on the buffer size (which needs to be a compile-time parameter).

More importantly, it will allow upgrading even when the serialized data is larger than the buffer size. Large buffer size = more efficient serialization (less IC calls) but less heap space for the canister. Small buffer size = inefficient serialization (lots of IC calls) but more heap space for the canister.

We could also allow tweaking buffer size in runtime, I'm not sure if this will be useful or needed though.

**Comment by crusso** [comment]
In 0.6.13 (not shipped with any dfx) we actually made the compacting gc the default. Should we make the copying collector the default again instead? Until we've fixed this issue with the compacting gc?

**Comment by osa1** [comment]
What is the process for shipping a release with dfx? If we can avoid shipping this version with dfx, then perhaps we still have the time to implement buffered serialization.

**Comment by osa1** [comment]
That said, until we revert the GC switch or fix this issue for good we won't be able to ship a newer version with dfx, so I think it makes sense to revert the GC as fixing this issue might take some time.

**Comment by crusso** [comment]
FTR The other trick I mentioned in the meeting was to trigger a gc treating just the stable variables as roots before doing the serialization in pre-upgrade, in the hope of freeing up space from non-stable variables.

Has the downside of requiring a gc in pre-upgrade, which is new and may run out of cycles.
